# Generated by Django 2.2.24 on 2021-07-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210721_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='createdat',
            new_name='created_at',
        ),
    ]
