# Generated by Django 2.2.24 on 2021-08-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='level',
            field=models.CharField(choices=[('1', '易'), ('2', 'やや易'), ('3', '普通'), ('4', 'やや難'), ('5', '難')], default='', max_length=5, verbose_name='難易度(易 1〜5 難)'),
        ),
    ]
