# Generated by Django 2.2.24 on 2021-08-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210809_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Game_monster',
        ),
    ]
