# Generated by Django 2.2.24 on 2021-08-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210809_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_monster',
            name='hp',
            field=models.PositiveIntegerField(default=1, verbose_name='HP'),
            preserve_default=False,
        ),
    ]
