# Generated by Django 2.2.24 on 2021-08-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='User',
        ),
    ]
