# Generated by Django 2.2.24 on 2021-08-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20210812_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
