# Generated by Django 2.2.24 on 2021-08-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attack',
        ),
    ]
