# Generated by Django 2.2.24 on 2021-08-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_remove_user_attack'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyArmorHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具名\u3000頭')),
                ('attackPower', models.IntegerField(blank=True, default=0, null=True, verbose_name='攻撃力')),
                ('defensePower', models.IntegerField(blank=True, default=0, null=True, verbose_name='防御力')),
                ('hpRecoveryPower', models.IntegerField(blank=True, default=0, null=True, verbose_name='HP回復力')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='購入額')),
                ('num', models.IntegerField(blank=True, default=0, null=True, verbose_name='所持数')),
            ],
        ),
        migrations.CreateModel(
            name='MyArmorLower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具名\u3000下')),
                ('attackPower', models.IntegerField(blank=True, default=0, null=True, verbose_name='攻撃力')),
                ('defensePower', models.IntegerField(blank=True, default=0, null=True, verbose_name='防御力')),
                ('hpRecoveryPower', models.IntegerField(blank=True, default=0, null=True, verbose_name='HP回復力')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='購入額')),
                ('num', models.IntegerField(blank=True, default=0, null=True, verbose_name='所持数')),
            ],
        ),
        migrations.CreateModel(
            name='MyArmorUpper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具名\u3000上')),
                ('attackPower', models.IntegerField(blank=True, default=0, null=True, verbose_name='攻撃力')),
                ('defensePower', models.IntegerField(blank=True, default=0, null=True, verbose_name='防御力')),
                ('hpRecoveryPower', models.IntegerField(blank=True, default=0, null=True, verbose_name='HP回復力')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='購入額')),
                ('num', models.IntegerField(blank=True, default=0, null=True, verbose_name='所持数')),
            ],
        ),
        migrations.CreateModel(
            name='MyWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='武器名')),
                ('attackPower', models.IntegerField(blank=True, default=0, null=True, verbose_name='攻撃力')),
                ('defensePower', models.IntegerField(blank=True, default=0, null=True, verbose_name='防御力')),
                ('hpRecoveryPower', models.IntegerField(blank=True, default=0, null=True, verbose_name='HP回復力')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='購入額')),
                ('num', models.IntegerField(blank=True, default=0, null=True, verbose_name='所持数')),
            ],
        ),
        migrations.CreateModel(
            name='CharData2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='名前')),
                ('myHP', models.IntegerField(blank=True, default=0, null=True, verbose_name='HP')),
                ('myLevel', models.IntegerField(blank=True, default=0, null=True, verbose_name='レベル')),
                ('myMoney', models.IntegerField(blank=True, default=0, null=True, verbose_name='持ち金')),
                ('myArmorHead', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorHead', verbose_name='防具\u3000頭')),
                ('myArmorLower', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorLower', verbose_name='防具\u3000下')),
                ('myArmorUpper', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorUpper', verbose_name='防具\u3000上')),
                ('myWeapon', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyWeapon', verbose_name='武器')),
            ],
        ),
        migrations.CreateModel(
            name='CharData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='名前')),
                ('myHP', models.IntegerField(blank=True, default=0, null=True, verbose_name='HP')),
                ('myLevel', models.IntegerField(blank=True, default=0, null=True, verbose_name='レベル')),
                ('myMoney', models.IntegerField(blank=True, default=0, null=True, verbose_name='持ち金')),
                ('myArmorHead', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorHead', verbose_name='防具\u3000頭')),
                ('myArmorLower', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorLower', verbose_name='防具\u3000下')),
                ('myArmorUpper', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorUpper', verbose_name='防具\u3000上')),
                ('myWeapon', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyWeapon', verbose_name='武器')),
            ],
        ),
    ]
