# Generated by Django 2.2.24 on 2021-08-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_chardata_chardata2_myarmorhead_myarmorlower_myarmorupper_myweapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='armorHead',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorHead', verbose_name='防具\u3000頭'),
        ),
        migrations.AddField(
            model_name='user',
            name='armorLower',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorLower', verbose_name='防具\u3000下'),
        ),
        migrations.AddField(
            model_name='user',
            name='armorUpper',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorUpper', verbose_name='防具\u3000上'),
        ),
        migrations.AddField(
            model_name='user',
            name='brave_name',
            field=models.CharField(blank=True, default='勇者くん', max_length=50, null=True, verbose_name='名前'),
        ),
        migrations.AddField(
            model_name='user',
            name='hp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HP'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='レベル'),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='持ち金'),
        ),
        migrations.AddField(
            model_name='user',
            name='weapon',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyWeapon', verbose_name='武器'),
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brave_name', models.CharField(blank=True, default='勇者くん', max_length=50, null=True, verbose_name='名前')),
                ('hp', models.IntegerField(blank=True, default=0, null=True, verbose_name='HP')),
                ('level', models.IntegerField(blank=True, default=0, null=True, verbose_name='レベル')),
                ('money', models.IntegerField(blank=True, default=0, null=True, verbose_name='持ち金')),
                ('armorHead', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorHead', verbose_name='防具\u3000頭')),
                ('armorLower', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorLower', verbose_name='防具\u3000下')),
                ('armorUpper', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorUpper', verbose_name='防具\u3000上')),
                ('weapon', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='todo.MyWeapon', verbose_name='武器')),
            ],
        ),
    ]
