# Generated by Django 2.2.24 on 2021-08-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_auto_20210826_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarmorhead',
            name='defensePower',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='防御力'),
        ),
        migrations.AlterField(
            model_name='myarmorhead',
            name='hpRecoveryPower',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='HP回復力'),
        ),
        migrations.AlterField(
            model_name='myarmorhead',
            name='myName',
            field=models.CharField(blank=True, default='布の帽子', max_length=50, null=True, verbose_name='防具名\u3000頭'),
        ),
        migrations.AlterField(
            model_name='myarmorhead',
            name='price',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='購入額'),
        ),
        migrations.AlterField(
            model_name='myweapon',
            name='attackPower',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='攻撃力'),
        ),
        migrations.AlterField(
            model_name='myweapon',
            name='myName',
            field=models.CharField(blank=True, default='木刀', max_length=50, null=True, verbose_name='武器名'),
        ),
        migrations.AlterField(
            model_name='myweapon',
            name='price',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='購入額'),
        ),
    ]
