# Generated by Django 2.2.24 on 2021-08-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_auto_20210826_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attack',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='attack'),
        ),
        migrations.AddField(
            model_name='user2',
            name='attack',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='attack'),
        ),
    ]
