# Generated by Django 2.2.24 on 2021-08-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_auto_20210828_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarmorlower',
            name='myName',
            field=models.CharField(blank=True, default='衣下', max_length=50, null=True, verbose_name='防具名\u3000下'),
        ),
        migrations.AlterField(
            model_name='myarmorupper',
            name='myName',
            field=models.CharField(blank=True, default='衣上', max_length=50, null=True, verbose_name='防具名\u3000上'),
        ),
    ]
