# Generated by Django 2.2.24 on 2021-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_auto_20210828_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarmorhead',
            name='myName',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具名\u3000頭'),
        ),
        migrations.AlterField(
            model_name='myarmorlower',
            name='myName',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具名\u3000下'),
        ),
        migrations.AlterField(
            model_name='myarmorupper',
            name='myName',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具名\u3000上'),
        ),
        migrations.AlterField(
            model_name='myweapon',
            name='myName',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='武器名'),
        ),
    ]
