# Generated by Django 2.2.24 on 2021-09-05 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0024_auto_20210902_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='myweapon',
            name='myTopimage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images', verbose_name='トップ画像'),
            preserve_default=False,
        ),
    ]
