# Generated by Django 2.2.24 on 2021-09-15 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0025_myweapon_mytopimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myweapon',
            name='myTopimage',
        ),
    ]
