# Generated by Django 2.2.24 on 2021-09-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_remove_myweapon_mytopimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='game_monster',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='game_monster',
            name='name',
        ),
    ]
