# Generated by Django 2.2.24 on 2021-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_auto_20210915_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='名前')),
                ('myHP', models.IntegerField(blank=True, default=0, null=True, verbose_name='HP')),
                ('myLevel', models.IntegerField(blank=True, default=0, null=True, verbose_name='レベル')),
                ('myWeapon', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='武器')),
                ('myArmorHead', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具\u3000頭')),
                ('myArmorUpper', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具\u3000上')),
                ('myArmorLower', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具\u3000下')),
                ('myArmorAccessory', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具\u3000アクセサリ')),
                ('myMoney', models.IntegerField(blank=True, default=0, null=True, verbose_name='持ち金')),
            ],
        ),
    ]
