# Generated by Django 2.2.24 on 2021-09-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_chardata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='user2',
            name='attack',
        ),
    ]
