# Generated by Django 2.2.24 on 2021-09-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0029_auto_20210915_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task_counter',
            new_name='Game',
        ),
        migrations.DeleteModel(
            name='Game_monster',
        ),
    ]
