# Generated by Django 2.2.24 on 2021-09-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0031_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharData',
        ),
        migrations.RemoveField(
            model_name='user2',
            name='armorHead',
        ),
        migrations.RemoveField(
            model_name='user2',
            name='armorLower',
        ),
        migrations.RemoveField(
            model_name='user2',
            name='armorUpper',
        ),
        migrations.RemoveField(
            model_name='user2',
            name='weapon',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User2',
        ),
    ]
