# Generated by Django 2.2.24 on 2021-09-26 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0032_auto_20210927_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='名前')),
                ('myHP', models.IntegerField(blank=True, default=0, null=True, verbose_name='HP')),
                ('myLevel', models.IntegerField(blank=True, default=0, null=True, verbose_name='レベル')),
                ('myWeapon', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='武器')),
                ('myArmorHead', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具\u3000頭')),
                ('myArmorUpper', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具\u3000上')),
                ('myArmorLower', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具\u3000下')),
                ('myArmorAccessory', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='防具\u3000アクセサリ')),
                ('myMoney', models.IntegerField(blank=True, default=0, null=True, verbose_name='持ち金')),
            ],
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brave_name', models.CharField(blank=True, default='勇者くん', max_length=50, null=True, verbose_name='名前')),
                ('hp', models.IntegerField(blank=True, default=100, null=True, verbose_name='HP')),
                ('level', models.IntegerField(blank=True, default=1, null=True, verbose_name='レベル')),
                ('money', models.IntegerField(blank=True, default=1000, null=True, verbose_name='持ち金')),
                ('armorHead', models.ForeignKey(default='布の帽子', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorHead', verbose_name='防具\u3000頭')),
                ('armorLower', models.ForeignKey(default='衣下', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorLower', verbose_name='防具\u3000下')),
                ('armorUpper', models.ForeignKey(default='衣上', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorUpper', verbose_name='防具\u3000上')),
                ('weapon', models.ForeignKey(default='木刀', on_delete=django.db.models.deletion.PROTECT, to='todo.MyWeapon', verbose_name='武器')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brave_name', models.CharField(blank=True, default='勇者くん', max_length=50, null=True, verbose_name='名前')),
                ('hp', models.IntegerField(blank=True, default=100, null=True, verbose_name='HP')),
                ('level', models.IntegerField(blank=True, default=1, null=True, verbose_name='レベル')),
                ('money', models.IntegerField(blank=True, default=1000, null=True, verbose_name='持ち金')),
                ('armorHead', models.ForeignKey(default='布の帽子', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorHead', verbose_name='防具\u3000頭')),
                ('armorLower', models.ForeignKey(default='衣下', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorLower', verbose_name='防具\u3000下')),
                ('armorUpper', models.ForeignKey(default='衣上', on_delete=django.db.models.deletion.PROTECT, to='todo.MyArmorUpper', verbose_name='防具\u3000上')),
                ('weapon', models.ForeignKey(default='木刀', on_delete=django.db.models.deletion.PROTECT, to='todo.MyWeapon', verbose_name='武器')),
            ],
        ),
    ]
