# Generated by Django 2.2.24 on 2021-10-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0033_chardata_user_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manekin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
