# Generated by Django 2.2.24 on 2021-10-28 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0034_manekin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('taskNo', models.IntegerField(blank=True, default=1, null=True, verbose_name='タスクＮＯ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('deadline_date', models.DateTimeField(blank=True, null=True, verbose_name='締切日')),
                ('complete_date', models.DateTimeField(blank=True, null=True, verbose_name='完了日')),
                ('level', models.CharField(choices=[('1', '易'), ('2', 'やや易'), ('3', '普通'), ('4', 'やや難'), ('5', '難')], default='', max_length=5, verbose_name='難易度(易 1〜5 難)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='CharData',
        ),
    ]
