# Generated by Django 2.2.24 on 2021-10-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0037_auto_20211029_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsterlog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='monsterlog',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='monsterlog',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='monsterlog',
            name='level',
        ),
        migrations.RemoveField(
            model_name='monsterlog',
            name='taskNo',
        ),
        migrations.RemoveField(
            model_name='monsterlog',
            name='title',
        ),
    ]
