# Generated by Django 2.2.24 on 2021-10-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0038_auto_20211029_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonsterLog',
            new_name='BattleLog',
        ),
    ]
