# Generated by Django 2.2.24 on 2021-10-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0040_auto_20211029_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='taskCompNum',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='タスク完了数'),
        ),
    ]
